repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
            stages: [commit]
          - id: end-of-file-fixer
            stages: [commit]
          - id: trailing-whitespace
            stages: [commit]
          - id: detect-private-key
            stages: [commit]
          - id: check-merge-conflict
            stages: [commit]
    - repo: https://github.com/golangci/golangci-lint
      rev: v1.52.0
      hooks:
          - id: golangci-lint
            stages: [commit]
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.0
      hooks:
          - id: go-fmt
            stages: [commit]
          - id: go-imports
            stages: [commit]
          - id: no-go-testing
            stages: [commit]
          - id: go-unit-tests
            stages: [commit]
    - repo: local
      hooks:
          - id: go-test
            name: go test
            description: This hook runs go test.
            entry: go test -v ./...
            language: golang
            stages: [commit]
    - repo: local
      hooks:
          - id: pre-commit-message
            name: commit-message lint
            description: This hook runs pre-commit-message check.
            entry: python3 contrib/commit-message-lint/commit-message-lint.py
            language: python
            stages: [commit-msg]
